# baseUrl = audio-to-script-backend-production.up.railway.app

# @name uploadRecord
POST http://localhost:3000/api/upload_record
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="record"; filename="sam-fowler-air.mp3"
Content-Type: audio/wav

< ./upload/sam-fowler-air.mp3
--Boundary--

###
# @name getTranscript
POST http://localhost:3000/api/get_transcript
Content-Type: application/json

{
    "file_name": "{{uploadRecord.response.body.file_name}}"
}

###
# @name getScript
GET  http://localhost:3000/api/get_script?fileName=rvq55fqv.json
# {{uploadRecord.response.body.file_name}}
Content-Type: application/json

###
GET http://localhost:3000/status
